#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-semver
Version  : 1.1.1
Release  : 1
URL      : https://github.com/swiftzer/semver/archive/v1.1.1.tar.gz
Source0  : https://github.com/swiftzer/semver/archive/v1.1.1.tar.gz
Source1  : https://plugins.gradle.org/m2/net/swiftzer/semver/semver/1.1.1/semver-1.1.1.jar
Source2  : https://plugins.gradle.org/m2/net/swiftzer/semver/semver/1.1.1/semver-1.1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-semver-data = %{version}-%{release}
Requires: mvn-semver-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
# SemVer
[![Build Status](https://travis-ci.org/swiftzer/semver.svg?branch=master)](https://travis-ci.org/swiftzer/semver)
[![codecov](https://codecov.io/gh/swiftzer/semver/branch/master/graph/badge.svg)](https://codecov.io/gh/swiftzer/semver)
[ ![Download](https://api.bintray.com/packages/swiftzer/maven/semver/images/download.svg) ](https://bintray.com/swiftzer/maven/semver/_latestVersion)

%package data
Summary: data components for the mvn-semver package.
Group: Data

%description data
data components for the mvn-semver package.


%package license
Summary: license components for the mvn-semver package.
Group: Default

%description license
license components for the mvn-semver package.


%prep
%setup -q -n semver-1.1.1

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-semver
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-semver/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/swiftzer/semver/semver/1.1.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/swiftzer/semver/semver/1.1.1/semver-1.1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/swiftzer/semver/semver/1.1.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/swiftzer/semver/semver/1.1.1/semver-1.1.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/swiftzer/semver/semver/1.1.1/semver-1.1.1.jar
/usr/share/java/.m2/repository/net/swiftzer/semver/semver/1.1.1/semver-1.1.1.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-semver/LICENSE
